"""CLI entry point for party setup, enemy setup, and turn-based combat."""

import time
from random import choice

from character import Character
from classes import Barbarian, Cleric, Fighter, Rogue, Sorcerer, Wizard
from enemies import DragonFactory, Enemy, GoblinFactory, SkeletonFactory, spawn_enemy

CLASSES: dict = {
    "barbarian": Barbarian,
    "cleric": Cleric,
    "wizard": Wizard,
    "sorcerer": Sorcerer,
    "fighter": Fighter,
    "rogue": Rogue,
}

ENEMIES: dict = {
    "goblin": GoblinFactory,
    "skeleton": SkeletonFactory,
    "dragon": DragonFactory,
}


def import_character():
    """Parse a saved character sheet and reconstruct a playable character.

    This function expects the export format generated by ``export_char_sheet``.
    It rebuilds a class instance first, then overwrites serialized fields to
    preserve exact saved state (HP, inventory, level, and stats).
    """
    filename: str = input("What is the full filename for this character sheet? ").strip()
    with open(filename, "r") as file:
        file_list = [line.rstrip("\n") for line in file]

    # Header format: "<name> - <race> <class> - level <N>"
    split_line: list[str] = file_list[0].strip().split(" - ")
    race_and_class: list[str] = split_line[1].split(" ", maxsplit=1)
    level_number: str = split_line[2].split(" ")[1]

    name = split_line[0]
    race = race_and_class[0]
    class_name = race_and_class[1]
    level = int(level_number)

    fields: dict[str, str] = {}
    items: dict[str, int] = {}

    # Parse two sections: character fields, then inventory lines.
    in_inventory = False
    for line in file_list[1:]:
        stripped = line.strip()
        if not stripped or set(stripped) == {"-"}:
            continue
        if stripped == "Inventory:":
            in_inventory = True
            continue
        if in_inventory:
            quantity, item_name = stripped.split(" ", maxsplit=1)
            items[item_name] = int(quantity)
            continue

        label, value = stripped.split(": ", maxsplit=1)
        fields[label] = value

    current, hp = (int(value) for value in fields["Health"].split("/", maxsplit=1))

    # Build the correct subclass, then replace randomized values with saved data.
    player = CLASSES[class_name](name, race, display=False)
    player.level = level
    player.exp = int(fields.get("Experience", 0))
    player.current_hp = current
    player.max_hp = hp
    player.passed_out = current <= 0
    player.strength = int(fields["Strength"])
    player.dexterity = int(fields["Dexterity"])
    player.constitution = int(fields["Constitution"])
    player.intelligence = int(fields["Intelligence"])
    player.wisdom = int(fields["Wisdom"])
    player.charisma = int(fields["Charisma"])
    player.inventory = items

    return player


def battle_loop():
    """Create characters and enemies, then execute the full battle loop.

    The loop alternates enemy turns and player turns until one side is defeated.
    """
    while True:
        try:
            amount: int = int(input("How many players? Enter a digit of up to 6. ").strip())
        except ValueError:
            print("Not a number, please try again.\n")
            continue
        if amount < 1 or amount > 6:
            print("Not a valid amount, please try again.\n")
            continue
        break

    players = {}
    import_answer = input("Would you like to import a character sheet? (y/n) ").strip().lower()
    while True:
        if import_answer == "y":
            player = import_character()
            players[player.name] = player
            another = input("Do you have another character to import? (y/n) ").strip().lower()
            if another != "y":
                break
            else:
                continue
        else:
            break

    for _ in range(amount - len(players)):
        while True:
            class_choice: str = (
                input(
                    f"Which class for player #{len(players)+1}?\nBarbarian, Cleric, Wizard, Sorcerer, Fighter, or Rogue "
                )
                .lower()
                .strip()
            )

            if class_choice not in CLASSES:
                print("Not a valid class option, please try again.\n")
                continue

            character: Character = CLASSES[class_choice].from_prompt()
            players[character.name] = character
            break

    print("The party:")
    for player in players.values():
        print(
            f"{player.name} - {player.race} {player.class_name} - level {player.level} - {player.hit_dice} hit dice - {player.max_hp} HP"
        )
    print()

    # Enemy creation is separate from player creation to keep setup readable.
    enemies = {}
    while True:
        try:
            num_enemies = int(input("How many enemies are there? ").strip())
        except ValueError:
            print("Not a number, please try again.\n")
            continue
        if num_enemies <= 0:
            print("Please enter at least 1 enemy.\n")
            continue
        break

    while True:
        enemy_type = (
            input("What type of enemy do you have?\nGoblin\nSkeleton\nDragon\n").lower().strip()
        )
        if enemy_type not in ENEMIES:
            print("Please choose one of the available enemy types.")
            continue

        else:
            enemy: Enemy = spawn_enemy(ENEMIES[enemy_type]())
            enemies[enemy] = num_enemies
            print(f"Spawned {num_enemies} {enemy}\n")
            time.sleep(2)
            break

    # Main combat loop: enemies attack first each round, then players retaliate.
    while enemies[enemy] > 0:
        active_players: list = [p for p in players.values() if p.current_hp > 0]

        if not active_players:
            print("All of your characters have died!")
            print(f"{enemies[enemy]} enemies remained.")
            break

        for _ in range(enemies[enemy]):
            if not enemy.passed_out:
                enemy.cause_dmg(choice(active_players))
                time.sleep(2)

        # Skip passed-out players so they do not act until revived.
        active_players = [p for p in players.values() if p.current_hp > 0]
        done: bool = False

        for player in active_players:
            for enemy in enemies.keys():
                if not player.passed_out and not enemy.passed_out:
                    player.cause_dmg(enemy)
                    time.sleep(2)

                if enemy.passed_out:
                    enemies[enemy] -= 1

                    if enemies[enemy] > 0:
                        enemy.passed_out = False
                        enemy.current_hp = enemy.max_hp
                        print(
                            f"Another enemy steps forward! {enemies[enemy]} of the enemies remain.\n"
                        )
                        time.sleep(2)

                    else:
                        print(f"Every enemy has been defeated!")
                        time.sleep(2)
                        done = True
                        break
            if done:
                for character in active_players:
                    character.current_hp = character.max_hp
                break

    export_choice: str = (
        input('Would you like to export your character sheets? Type "yes" or "y" ').lower().strip()
    )
    if export_choice == "yes" or export_choice == "y":
        for character in players.values():
            character.export_char_sheet()
    else:
        print("Characters not saved. Thanks for playing!")


if __name__ == "__main__":
    battle_loop()
